/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIndexRouteImport } from './routes/listings.index'
import { Route as DealsIndexRouteImport } from './routes/deals.index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as WalletWithdrawRouteImport } from './routes/wallet.withdraw'
import { Route as WalletTransferRouteImport } from './routes/wallet.transfer'
import { Route as WalletDepositRouteImport } from './routes/wallet.deposit'
import { Route as SettingsDealCodeRouteImport } from './routes/settings.deal-code'
import { Route as OnboardingDealCodeRouteImport } from './routes/onboarding.deal-code'
import { Route as MerchantUserIdRouteImport } from './routes/merchant.$userId'
import { Route as ListingsNewRouteImport } from './routes/listings.new'
import { Route as DealsDealIdRouteImport } from './routes/deals.$dealId'
import { Route as ChatConversationIdRouteImport } from './routes/chat.$conversationId'
import { Route as DealsNewListingIdRouteImport } from './routes/deals.new.$listingId'
import { Route as ApiWalletWithdrawRouteImport } from './routes/api/wallet/withdraw'
import { Route as ApiWalletTransferRouteImport } from './routes/api/wallet/transfer'
import { Route as ApiWalletDepositAddressRouteImport } from './routes/api/wallet/deposit-address'
import { Route as ApiDealsReleaseRouteImport } from './routes/api/deals/release'
import { Route as ApiDealCodeSetRouteImport } from './routes/api/deal-code/set'
import { Route as ApiDealCodeRequestOtpRouteImport } from './routes/api/deal-code/request-otp'
import { Route as ApiDealCodeChangeRouteImport } from './routes/api/deal-code/change'
import { Route as ApiDealCodeBiometricRouteImport } from './routes/api/deal-code/biometric'
import { Route as ApiPublicWebhooksNowpaymentsRouteImport } from './routes/api/public/webhooks/nowpayments'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIndexRoute = DealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletWithdrawRoute = WalletWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => WalletRoute,
} as any)
const WalletTransferRoute = WalletTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => WalletRoute,
} as any)
const WalletDepositRoute = WalletDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => WalletRoute,
} as any)
const SettingsDealCodeRoute = SettingsDealCodeRouteImport.update({
  id: '/deal-code',
  path: '/deal-code',
  getParentRoute: () => SettingsRoute,
} as any)
const OnboardingDealCodeRoute = OnboardingDealCodeRouteImport.update({
  id: '/onboarding/deal-code',
  path: '/onboarding/deal-code',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantUserIdRoute = MerchantUserIdRouteImport.update({
  id: '/merchant/$userId',
  path: '/merchant/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsNewRoute = ListingsNewRouteImport.update({
  id: '/listings/new',
  path: '/listings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsDealIdRoute = DealsDealIdRouteImport.update({
  id: '/deals/$dealId',
  path: '/deals/$dealId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatConversationIdRoute = ChatConversationIdRouteImport.update({
  id: '/chat/$conversationId',
  path: '/chat/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsNewListingIdRoute = DealsNewListingIdRouteImport.update({
  id: '/deals/new/$listingId',
  path: '/deals/new/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletWithdrawRoute = ApiWalletWithdrawRouteImport.update({
  id: '/api/wallet/withdraw',
  path: '/api/wallet/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletTransferRoute = ApiWalletTransferRouteImport.update({
  id: '/api/wallet/transfer',
  path: '/api/wallet/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletDepositAddressRoute = ApiWalletDepositAddressRouteImport.update({
  id: '/api/wallet/deposit-address',
  path: '/api/wallet/deposit-address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDealsReleaseRoute = ApiDealsReleaseRouteImport.update({
  id: '/api/deals/release',
  path: '/api/deals/release',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDealCodeSetRoute = ApiDealCodeSetRouteImport.update({
  id: '/api/deal-code/set',
  path: '/api/deal-code/set',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDealCodeRequestOtpRoute = ApiDealCodeRequestOtpRouteImport.update({
  id: '/api/deal-code/request-otp',
  path: '/api/deal-code/request-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDealCodeChangeRoute = ApiDealCodeChangeRouteImport.update({
  id: '/api/deal-code/change',
  path: '/api/deal-code/change',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDealCodeBiometricRoute = ApiDealCodeBiometricRouteImport.update({
  id: '/api/deal-code/biometric',
  path: '/api/deal-code/biometric',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksNowpaymentsRoute =
  ApiPublicWebhooksNowpaymentsRouteImport.update({
    id: '/api/public/webhooks/nowpayments',
    path: '/api/public/webhooks/nowpayments',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/settings': typeof SettingsRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/merchant/$userId': typeof MerchantUserIdRoute
  '/onboarding/deal-code': typeof OnboardingDealCodeRoute
  '/settings/deal-code': typeof SettingsDealCodeRoute
  '/wallet/deposit': typeof WalletDepositRoute
  '/wallet/transfer': typeof WalletTransferRoute
  '/wallet/withdraw': typeof WalletWithdrawRoute
  '/chat/': typeof ChatIndexRoute
  '/deals/': typeof DealsIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/api/deal-code/biometric': typeof ApiDealCodeBiometricRoute
  '/api/deal-code/change': typeof ApiDealCodeChangeRoute
  '/api/deal-code/request-otp': typeof ApiDealCodeRequestOtpRoute
  '/api/deal-code/set': typeof ApiDealCodeSetRoute
  '/api/deals/release': typeof ApiDealsReleaseRoute
  '/api/wallet/deposit-address': typeof ApiWalletDepositAddressRoute
  '/api/wallet/transfer': typeof ApiWalletTransferRoute
  '/api/wallet/withdraw': typeof ApiWalletWithdrawRoute
  '/deals/new/$listingId': typeof DealsNewListingIdRoute
  '/api/public/webhooks/nowpayments': typeof ApiPublicWebhooksNowpaymentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/settings': typeof SettingsRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/merchant/$userId': typeof MerchantUserIdRoute
  '/onboarding/deal-code': typeof OnboardingDealCodeRoute
  '/settings/deal-code': typeof SettingsDealCodeRoute
  '/wallet/deposit': typeof WalletDepositRoute
  '/wallet/transfer': typeof WalletTransferRoute
  '/wallet/withdraw': typeof WalletWithdrawRoute
  '/chat': typeof ChatIndexRoute
  '/deals': typeof DealsIndexRoute
  '/listings': typeof ListingsIndexRoute
  '/api/deal-code/biometric': typeof ApiDealCodeBiometricRoute
  '/api/deal-code/change': typeof ApiDealCodeChangeRoute
  '/api/deal-code/request-otp': typeof ApiDealCodeRequestOtpRoute
  '/api/deal-code/set': typeof ApiDealCodeSetRoute
  '/api/deals/release': typeof ApiDealsReleaseRoute
  '/api/wallet/deposit-address': typeof ApiWalletDepositAddressRoute
  '/api/wallet/transfer': typeof ApiWalletTransferRoute
  '/api/wallet/withdraw': typeof ApiWalletWithdrawRoute
  '/deals/new/$listingId': typeof DealsNewListingIdRoute
  '/api/public/webhooks/nowpayments': typeof ApiPublicWebhooksNowpaymentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/settings': typeof SettingsRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/merchant/$userId': typeof MerchantUserIdRoute
  '/onboarding/deal-code': typeof OnboardingDealCodeRoute
  '/settings/deal-code': typeof SettingsDealCodeRoute
  '/wallet/deposit': typeof WalletDepositRoute
  '/wallet/transfer': typeof WalletTransferRoute
  '/wallet/withdraw': typeof WalletWithdrawRoute
  '/chat/': typeof ChatIndexRoute
  '/deals/': typeof DealsIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/api/deal-code/biometric': typeof ApiDealCodeBiometricRoute
  '/api/deal-code/change': typeof ApiDealCodeChangeRoute
  '/api/deal-code/request-otp': typeof ApiDealCodeRequestOtpRoute
  '/api/deal-code/set': typeof ApiDealCodeSetRoute
  '/api/deals/release': typeof ApiDealsReleaseRoute
  '/api/wallet/deposit-address': typeof ApiWalletDepositAddressRoute
  '/api/wallet/transfer': typeof ApiWalletTransferRoute
  '/api/wallet/withdraw': typeof ApiWalletWithdrawRoute
  '/deals/new/$listingId': typeof DealsNewListingIdRoute
  '/api/public/webhooks/nowpayments': typeof ApiPublicWebhooksNowpaymentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/marketplace'
    | '/settings'
    | '/transactions'
    | '/wallet'
    | '/chat/$conversationId'
    | '/deals/$dealId'
    | '/listings/new'
    | '/merchant/$userId'
    | '/onboarding/deal-code'
    | '/settings/deal-code'
    | '/wallet/deposit'
    | '/wallet/transfer'
    | '/wallet/withdraw'
    | '/chat/'
    | '/deals/'
    | '/listings/'
    | '/api/deal-code/biometric'
    | '/api/deal-code/change'
    | '/api/deal-code/request-otp'
    | '/api/deal-code/set'
    | '/api/deals/release'
    | '/api/wallet/deposit-address'
    | '/api/wallet/transfer'
    | '/api/wallet/withdraw'
    | '/deals/new/$listingId'
    | '/api/public/webhooks/nowpayments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/marketplace'
    | '/settings'
    | '/transactions'
    | '/wallet'
    | '/chat/$conversationId'
    | '/deals/$dealId'
    | '/listings/new'
    | '/merchant/$userId'
    | '/onboarding/deal-code'
    | '/settings/deal-code'
    | '/wallet/deposit'
    | '/wallet/transfer'
    | '/wallet/withdraw'
    | '/chat'
    | '/deals'
    | '/listings'
    | '/api/deal-code/biometric'
    | '/api/deal-code/change'
    | '/api/deal-code/request-otp'
    | '/api/deal-code/set'
    | '/api/deals/release'
    | '/api/wallet/deposit-address'
    | '/api/wallet/transfer'
    | '/api/wallet/withdraw'
    | '/deals/new/$listingId'
    | '/api/public/webhooks/nowpayments'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/marketplace'
    | '/settings'
    | '/transactions'
    | '/wallet'
    | '/chat/$conversationId'
    | '/deals/$dealId'
    | '/listings/new'
    | '/merchant/$userId'
    | '/onboarding/deal-code'
    | '/settings/deal-code'
    | '/wallet/deposit'
    | '/wallet/transfer'
    | '/wallet/withdraw'
    | '/chat/'
    | '/deals/'
    | '/listings/'
    | '/api/deal-code/biometric'
    | '/api/deal-code/change'
    | '/api/deal-code/request-otp'
    | '/api/deal-code/set'
    | '/api/deals/release'
    | '/api/wallet/deposit-address'
    | '/api/wallet/transfer'
    | '/api/wallet/withdraw'
    | '/deals/new/$listingId'
    | '/api/public/webhooks/nowpayments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  MarketplaceRoute: typeof MarketplaceRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TransactionsRoute: typeof TransactionsRoute
  WalletRoute: typeof WalletRouteWithChildren
  ChatConversationIdRoute: typeof ChatConversationIdRoute
  DealsDealIdRoute: typeof DealsDealIdRoute
  ListingsNewRoute: typeof ListingsNewRoute
  MerchantUserIdRoute: typeof MerchantUserIdRoute
  OnboardingDealCodeRoute: typeof OnboardingDealCodeRoute
  ChatIndexRoute: typeof ChatIndexRoute
  DealsIndexRoute: typeof DealsIndexRoute
  ListingsIndexRoute: typeof ListingsIndexRoute
  ApiDealCodeBiometricRoute: typeof ApiDealCodeBiometricRoute
  ApiDealCodeChangeRoute: typeof ApiDealCodeChangeRoute
  ApiDealCodeRequestOtpRoute: typeof ApiDealCodeRequestOtpRoute
  ApiDealCodeSetRoute: typeof ApiDealCodeSetRoute
  ApiDealsReleaseRoute: typeof ApiDealsReleaseRoute
  ApiWalletDepositAddressRoute: typeof ApiWalletDepositAddressRoute
  ApiWalletTransferRoute: typeof ApiWalletTransferRoute
  ApiWalletWithdrawRoute: typeof ApiWalletWithdrawRoute
  DealsNewListingIdRoute: typeof DealsNewListingIdRoute
  ApiPublicWebhooksNowpaymentsRoute: typeof ApiPublicWebhooksNowpaymentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/': {
      id: '/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/': {
      id: '/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof DealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/withdraw': {
      id: '/wallet/withdraw'
      path: '/withdraw'
      fullPath: '/wallet/withdraw'
      preLoaderRoute: typeof WalletWithdrawRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/transfer': {
      id: '/wallet/transfer'
      path: '/transfer'
      fullPath: '/wallet/transfer'
      preLoaderRoute: typeof WalletTransferRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/deposit': {
      id: '/wallet/deposit'
      path: '/deposit'
      fullPath: '/wallet/deposit'
      preLoaderRoute: typeof WalletDepositRouteImport
      parentRoute: typeof WalletRoute
    }
    '/settings/deal-code': {
      id: '/settings/deal-code'
      path: '/deal-code'
      fullPath: '/settings/deal-code'
      preLoaderRoute: typeof SettingsDealCodeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/onboarding/deal-code': {
      id: '/onboarding/deal-code'
      path: '/onboarding/deal-code'
      fullPath: '/onboarding/deal-code'
      preLoaderRoute: typeof OnboardingDealCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/$userId': {
      id: '/merchant/$userId'
      path: '/merchant/$userId'
      fullPath: '/merchant/$userId'
      preLoaderRoute: typeof MerchantUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/new': {
      id: '/listings/new'
      path: '/listings/new'
      fullPath: '/listings/new'
      preLoaderRoute: typeof ListingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$dealId': {
      id: '/deals/$dealId'
      path: '/deals/$dealId'
      fullPath: '/deals/$dealId'
      preLoaderRoute: typeof DealsDealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$conversationId': {
      id: '/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof ChatConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/new/$listingId': {
      id: '/deals/new/$listingId'
      path: '/deals/new/$listingId'
      fullPath: '/deals/new/$listingId'
      preLoaderRoute: typeof DealsNewListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet/withdraw': {
      id: '/api/wallet/withdraw'
      path: '/api/wallet/withdraw'
      fullPath: '/api/wallet/withdraw'
      preLoaderRoute: typeof ApiWalletWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet/transfer': {
      id: '/api/wallet/transfer'
      path: '/api/wallet/transfer'
      fullPath: '/api/wallet/transfer'
      preLoaderRoute: typeof ApiWalletTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet/deposit-address': {
      id: '/api/wallet/deposit-address'
      path: '/api/wallet/deposit-address'
      fullPath: '/api/wallet/deposit-address'
      preLoaderRoute: typeof ApiWalletDepositAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deals/release': {
      id: '/api/deals/release'
      path: '/api/deals/release'
      fullPath: '/api/deals/release'
      preLoaderRoute: typeof ApiDealsReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deal-code/set': {
      id: '/api/deal-code/set'
      path: '/api/deal-code/set'
      fullPath: '/api/deal-code/set'
      preLoaderRoute: typeof ApiDealCodeSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deal-code/request-otp': {
      id: '/api/deal-code/request-otp'
      path: '/api/deal-code/request-otp'
      fullPath: '/api/deal-code/request-otp'
      preLoaderRoute: typeof ApiDealCodeRequestOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deal-code/change': {
      id: '/api/deal-code/change'
      path: '/api/deal-code/change'
      fullPath: '/api/deal-code/change'
      preLoaderRoute: typeof ApiDealCodeChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deal-code/biometric': {
      id: '/api/deal-code/biometric'
      path: '/api/deal-code/biometric'
      fullPath: '/api/deal-code/biometric'
      preLoaderRoute: typeof ApiDealCodeBiometricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/nowpayments': {
      id: '/api/public/webhooks/nowpayments'
      path: '/api/public/webhooks/nowpayments'
      fullPath: '/api/public/webhooks/nowpayments'
      preLoaderRoute: typeof ApiPublicWebhooksNowpaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsDealCodeRoute: typeof SettingsDealCodeRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsDealCodeRoute: SettingsDealCodeRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface WalletRouteChildren {
  WalletDepositRoute: typeof WalletDepositRoute
  WalletTransferRoute: typeof WalletTransferRoute
  WalletWithdrawRoute: typeof WalletWithdrawRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletDepositRoute: WalletDepositRoute,
  WalletTransferRoute: WalletTransferRoute,
  WalletWithdrawRoute: WalletWithdrawRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  MarketplaceRoute: MarketplaceRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TransactionsRoute: TransactionsRoute,
  WalletRoute: WalletRouteWithChildren,
  ChatConversationIdRoute: ChatConversationIdRoute,
  DealsDealIdRoute: DealsDealIdRoute,
  ListingsNewRoute: ListingsNewRoute,
  MerchantUserIdRoute: MerchantUserIdRoute,
  OnboardingDealCodeRoute: OnboardingDealCodeRoute,
  ChatIndexRoute: ChatIndexRoute,
  DealsIndexRoute: DealsIndexRoute,
  ListingsIndexRoute: ListingsIndexRoute,
  ApiDealCodeBiometricRoute: ApiDealCodeBiometricRoute,
  ApiDealCodeChangeRoute: ApiDealCodeChangeRoute,
  ApiDealCodeRequestOtpRoute: ApiDealCodeRequestOtpRoute,
  ApiDealCodeSetRoute: ApiDealCodeSetRoute,
  ApiDealsReleaseRoute: ApiDealsReleaseRoute,
  ApiWalletDepositAddressRoute: ApiWalletDepositAddressRoute,
  ApiWalletTransferRoute: ApiWalletTransferRoute,
  ApiWalletWithdrawRoute: ApiWalletWithdrawRoute,
  DealsNewListingIdRoute: DealsNewListingIdRoute,
  ApiPublicWebhooksNowpaymentsRoute: ApiPublicWebhooksNowpaymentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
